export const CoinsActionTypes = {
  SET_COINS: 'SET_COINS',
  GET_SAVED_COINS_FROM_COINS: 'GET_SAVED_COINS_FROM_COINS',
  ADD_SAVED_COIN: 'ADD_SAVED_COIN',
  REMOVE_SAVED_COIN: 'REMOVE_SAVED_COIN',
};
