export const UserActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
  SIGN_IN_WITH_TOUCH_ID_START: 'SIGN_IN_WITH_TOUCH_ID_START',
  SIGN_IN_FAILED: 'SIGN_IN_FAILED',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
};
